#+TITLE: Vim config
#+STARTUP: content

* Installation Script
Setup a Vim environment with [[https://github.com/junegunn/vim-plug][vim-plug]].
I prioritize speed and simplicity in my Vim config, using Emacs for more involved tasks.

=vim-plug= will call =PlugInstall= automatically when vim first opens. It can be re-run manually with =:PlugInstall=.

Files generated:
- =~/.vim/autoload/plug.vim= :: curl'ed from junegunn's =vim-plug= github repo
- =~/.vim/plug/* :: the github repo for each plugin configured by the =Plug= command
- =~/.vim/vimrc :: symlink to out/vimrc

#+BEGIN_SRC sh :tangle sh/install-vim.sh
mkdir -p ~/.vim
ln -svf $PWD/out/vimrc ~/.vim/vimrc
#+END_SRC

* .vimrc
First, setup vim-plug if it does not exist.

#+BEGIN_SRC sh :tangle out/vimrc
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plug')
#+END_SRC

Install the [[https://github.com/drewtempelmeyer/palenight.vim][palenight]] colorscheme, customized [[Palenight colorscheme][below]].

#+BEGIN_SRC sh :tangle out/vimrc
Plug 'drewtempelmeyer/palenight.vim'
#+END_SRC

Install additional plugins.

#+BEGIN_SRC sh :tangle out/vimrc
Plug 'Raimondi/delimitMate' " automatic closing of quotes, parenthesis, brackets, etc. "
Plug 'airblade/vim-gitgutter' " shows git diff in the sign column "
#+END_SRC

Initialize the plugin system.

#+BEGIN_SRC sh :tangle out/vimrc
call plug#end()
#+END_SRC

Configure some general settings.

#+BEGIN_SRC sh :tangle out/vimrc
" Include line numbers "
set number

" Maintain current indentation on new line "
set autoindent

" Make tabs visible "
set list listchars=tab:__

" Soft wrap and break lines at word boundaries "
set wrap linebreak

" Display tabs with a width of 4 "
set tabstop=4

" Allow backspacing over autoindent, line breaks, and the start of insert "
set backspace=indent,eol,start

" Store viminfo under ~/.vim to keep homedir clean "
set viminfo+=n~/.vim/viminfo
#+END_SRC

** Palenight colorscheme
Configure the [[https://github.com/drewtempelmeyer/palenight.vim][palenight]] colorscheme. It supports lightline and airline should I
introduce either.

#+BEGIN_SRC sh :tangle out/vimrc
" palenight colorscheme configuration "
set background=dark
colorscheme palenight
let g:palenight_terminal_italics=1
#+END_SRC

On Linux, this will enable =termguicolors=, which is necessary for the terminal
palette to support the full requirements of palenight.

As described [[https://github.com/kaicataldo/material.vim#true-colors][here]], the default version of =vim= on =MacOS= doesn't support
=termguicolors=. To fix this, I chose to upgrade =vim= via =brew=, following
[[https://apple.stackexchange.com/questions/362833/make-homebrew-installed-vim-override-system-installed-one][these instructions]], and then configuring an alias to =/usr/local/bin/vim=.

#+BEGIN_SRC sh :tangle out/vimrc
"For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
  set termguicolors
endif
#+END_SRC

